[project]
name = "coach_calendar_sync"
authors = [
    { name = "The Resilient Kid", email = "support@theresilientkid.co.uk" }
]
description = "Google Calendar sync for Coaches and Session Workers"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "google-auth>=2.0.0",
    "google-auth-oauthlib>=1.0.0",
    "google-api-python-client>=2.0.0",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0"
